{"id":"xg2sbknzx92134vymjwoh8d","title":"Exception Handling","desc":"","updated":1708610897122,"created":1708610884501,"custom":{},"fname":"dev.issues.exception.handling","type":"note","vault":{"fsPath":".","selfContained":true,"name":"cs"},"contentHash":"51ca29866d3ce3455f7811ace81c1a4a","links":[{"type":"wiki","from":{"fname":"dev.issues.exception.handling","id":"xg2sbknzx92134vymjwoh8d","vaultName":"cs"},"value":"dev.issues.exception","position":{"start":{"line":2,"column":23,"offset":23},"end":{"line":2,"column":47,"offset":47},"indent":[]},"xvault":false,"sameFile":false,"to":{"fname":"dev.issues.exception"}}],"anchors":{},"children":[],"parent":"hphqd3qnjgeu9tgmwre3csz","data":{}}
